services:
  - type: web
    name: onlinemeat-6
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd Meatmart && gunicorn meatmart.wsgi:application --bind=0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: meatmart_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: meatmart.settings
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src/Meatmart

databases:
  - name: meatmart_db
    databaseName: meatmart
    user: meatmart
